[package]
name = "wigner_j"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[example]]
name = "ex_1"
path = "examples/ex_1.rs"

[[example]]
name = "ex_2"
path = "examples/ex_2.rs"

[dependencies]
