[package]
name = "transition"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[example]]
name = "ex_transition"
path = "examples/ex_transition.rs"

[dependencies]
wigner_j = {path = "../wigner_j"}
