[package]
name = "eigen_state"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[example]]
name = "ex_eigen_energy"
path = "examples/ex_eigen_energy.rs"

[dependencies]
